'use client';
import { Plus, Trash2 } from 'lucide-react';
import type { CampaignSettings, DonationMethod, Endorsement } from '@/lib/cms/types';
import { Field, ImageField } from './Fields';
export function SettingsEditor({ settings, onChange, mode }: { settings: CampaignSettings; onChange: (settings: CampaignSettings) => void; mode: 'donations' | 'backers' }) {
  function payment(id: string, update: Partial<DonationMethod>) { onChange({ ...settings, donationMethods: settings.donationMethods.map(item => item.id === id ? { ...item, ...update } : item) }); }
  function backer(id: string, update: Partial<Endorsement>) { onChange({ ...settings, supporters: settings.supporters.map(item => item.id === id ? { ...item, ...update } : item) }); }
  if (mode === 'donations') return <div className="admin-settings"><p className="admin-info">Enable a method only after verifying the receiving account. These are direct-transfer instructions or payment links; no transfer is marked paid by this site.</p>{settings.donationMethods.map(item => <section className="admin-block" key={item.id}><header><h3>{item.name || 'New payment method'}</h3><label className="admin-toggle"><input type="checkbox" checked={item.enabled} onChange={e => payment(item.id, { enabled: e.target.checked })} />Enabled</label></header><div className="admin-two-fields"><Field label="Method name" value={item.name} onChange={name => payment(item.id, { name })} /><label className="admin-field"><span>Type</span><select value={item.kind} onChange={e => payment(item.id, { kind: e.target.value as DonationMethod['kind'] })}><option value="mobile">Mobile money</option><option value="crypto">Crypto wallet</option><option value="link">Payment link</option></select></label><Field label="Receiving account name" value={item.recipient} onChange={recipient => payment(item.id, { recipient })} /><Field label="Currency" value={item.currency} onChange={currency => payment(item.id, { currency })} /></div>{item.kind === 'link' ? <Field label="Verified HTTPS payment link" value={item.url} onChange={url => payment(item.id, { url })} /> : <Field label={item.kind === 'crypto' ? 'Wallet address' : 'Receiving number / account'} value={item.account} onChange={account => payment(item.id, { account })} />}{item.kind === 'crypto' && <Field label="Exact network (required)" value={item.network} onChange={network => payment(item.id, { network })} hint="For example, use the exact network supported by your receiving wallet." />}<div className="admin-two-fields">{(['en', 'so'] as const).map(lang => <Field key={lang} label={`Instructions · ${lang === 'en' ? 'English' : 'Somali'}`} multiline value={item.instructions[lang]} onChange={value => payment(item.id, { instructions: { ...item.instructions, [lang]: value } })} />)}</div></section>)}<button type="button" className="admin-button admin-button-secondary" onClick={() => onChange({ ...settings, donationMethods: [...settings.donationMethods, { id: crypto.randomUUID(), name: '', kind: 'mobile', enabled: false, account: '', recipient: '', network: '', currency: 'USD', url: '', instructions: { en: '', so: '' } }] })}><Plus size={16} />Add payment method</button></div>;
  return <div className="admin-settings"><p className="admin-info">Add organisations that have agreed to publicly support the campaign. Logos retain their original proportions on the website.</p>{settings.supporters.length === 0 && <div className="admin-empty"><h3>Your supporting organisations belong here.</h3><p>Add a name, logo and optional website. Publish when ready to show them on Get Involved.</p></div>}{settings.supporters.map(item => <section className="admin-block" key={item.id}><header><h3>{item.name || 'New supporting entity'}</h3><div><label className="admin-toggle"><input type="checkbox" checked={item.visible} onChange={e => backer(item.id, { visible: e.target.checked })} />Visible</label><button type="button" className="admin-icon-button" aria-label="Remove supporting entity" onClick={() => onChange({ ...settings, supporters: settings.supporters.filter(s => s.id !== item.id) })}><Trash2 size={16} /></button></div></header><Field label="Organisation name" value={item.name} onChange={name => backer(item.id, { name })} /><ImageField label="Organisation logo" value={item.logo} onChange={logo => backer(item.id, { logo })} /><Field label="Website (optional)" value={item.url} onChange={url => backer(item.id, { url })} /><div className="admin-two-fields">{(['en', 'so'] as const).map(lang => <Field key={lang} label={`Description · ${lang === 'en' ? 'English' : 'Somali'}`} value={item.description[lang]} onChange={value => backer(item.id, { description: { ...item.description, [lang]: value } })} />)}</div></section>)}<button type="button" className="admin-button admin-button-secondary" onClick={() => onChange({ ...settings, supporters: [...settings.supporters, { id: crypto.randomUUID(), name: '', logo: '', url: '', visible: false, description: { en: '', so: '' } }] })}><Plus size={16} />Add supporting entity</button></div>;
}
